Fix: init memory

diff --git a/.github/workflows/k8s-testing.yml b/.github/workflows/k8s-testing.yml
--- a/.github/workflows/k8s-testing.yml
+++ b/.github/workflows/k8s-testing.yml
@@ -181,16 +181,18 @@ jobs:
       - name: Check Application
         run: |-
              to_complete () {
-               kubectl wait  --for=$1 $2 --timeout=500s --selector=$3
-               if [[ ${?} != 0 ]]; then
-                 echo "ERROR: $2"
-                 echo "INFO: status:"
-                 kubectl get pods
-                 echo "INFO: logs:"
-                 kubectl logs  --selector=$3
-               fi
-               return ${?}
-             }
+                kubectl wait --for=$1 $2 --timeout=500s --selector=$3 2>/tmp/test || true
+                if [[ -s /tmp/test ]]; then
+                echo "ERROR: "
+                cat /tmp/test
+                echo "INFO: status:"
+                kubectl get pods
+                echo "INFO: logs:"
+                kubectl logs  --selector=$3 --all-containers=true
+                exit 1
+                fi
+                return ${?}
+                }
              echo "Waiting for init job..."
              to_complete  "condition=Complete" job "defectdojo.org/component=initializer"
              echo "Waiting for celery pods..."
